In [1]:
import numpy as np

## Part B

In [2]:
hiddenWeights = np.matrix('2 0 3 3 7; 0 -3 3 3 4; -3 3 -2 0 2; -2 6 0 -3 5')
print(hiddenWeights)

[[ 2  0  3  3  7]
 [ 0 -3  3  3  4]
 [-3  3 -2  0  2]
 [-2  6  0 -3  5]]


In [3]:
inputs = np.zeros([16,5])
i3 = -1
i2 = -1
i1 = -1
i0 = -1

for i in range(16):
    inputs[i,0] = i0
    inputs[i,1] = i1
    inputs[i,2] = i2
    inputs[i,3] = i3
    
    i3 = -i3
    if(i % 2):
        i2 = -i2
    if(i % 4 == 3):
        i1 = -i1
    if(i % 8 == 7):
        i0 = -i0
inputs[inputs < 0] = 0
inputs[:,4] = -1
print(inputs)

[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  0.  1.  1. -1.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  1.  0.  1. -1.]
 [ 0.  1.  1.  0. -1.]
 [ 0.  1.  1.  1. -1.]
 [ 1.  0.  0.  0. -1.]
 [ 1.  0.  0.  1. -1.]
 [ 1.  0.  1.  0. -1.]
 [ 1.  0.  1.  1. -1.]
 [ 1.  1.  0.  0. -1.]
 [ 1.  1.  0.  1. -1.]
 [ 1.  1.  1.  0. -1.]
 [ 1.  1.  1.  1. -1.]]


In [4]:
def unitStep(x):
    x[x >= 0] = 1
    x[x < 0] = 0
    y = x
    return y

In [5]:
hiddenOuts = unitStep(np.matmul(hiddenWeights,inputs.T))
print(hiddenOuts)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
hiddenOuts = hiddenOuts.T
outBiases = np.ones([16,1])
outBiases[outBiases > 0] = -1
hiddenOuts = np.concatenate((hiddenOuts, outBiases), axis=1)
print(hiddenOuts)

[[ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  1. -1.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 1.  1.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1.]
 [ 1.  0.  0.  0. -1.]]


In [7]:
outWeights = np.matrix('2 3 4 5 1')
print(outWeights.shape)

(1, 5)


In [8]:
outs = unitStep(np.matmul(outWeights, hiddenOuts.T))

In [9]:
print(outs)

[[0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1.]]


In [10]:
def xor(x1, x2):
    return (x1 and (not x2)) or ((not x1) and x2)

def logicFnc(x):
    return xor(x[0] or (not x[1]), (not x[2]) or (not x[3]))

In [11]:
inputsCheck = inputs[:,0:4]
checkOuts = list()

for i in range(16):
    checkOuts.append(logicFnc(inputsCheck[i,:]))

print(checkOuts)

[False, False, False, True, True, True, True, False, False, False, False, True, False, False, False, True]


In [12]:
print((outs == checkOuts).all())

True


## Part D

In [13]:
hiddenWeightsRobust = np.matrix('1 0 1 1 2.5; 0 -1 1 1 1.5; -1 1 -1 0 0.5; -1 1 0 -1 0.5')
print(hiddenWeightsRobust)

[[ 1.   0.   1.   1.   2.5]
 [ 0.  -1.   1.   1.   1.5]
 [-1.   1.  -1.   0.   0.5]
 [-1.   1.   0.  -1.   0.5]]


In [14]:
inputsRobust = np.zeros([400,5])
for i in range(16):
    for j in range(25):
        inputsRobust[i*25+j,:] = inputs[i]
print(inputsRobust.shape)

(400, 5)


In [15]:
meanPrm = 0
stdPrm = 0.2
noiseMatrix = np.random.normal(meanPrm, stdPrm, 2000).reshape(400,5) 
noiseMatrix[:,4] = 0
print(noiseMatrix.shape)

(400, 5)


In [16]:
inputsNoise = inputsRobust + noiseMatrix

In [17]:
hiddenOutsRobust = unitStep(np.matmul(hiddenWeightsRobust,inputsNoise.T))
hiddenOutsRobust = hiddenOutsRobust.T
outBiases = np.ones([400,1])
outBiases[outBiases > 0] = -1
hiddenOutsRobust = np.concatenate((hiddenOutsRobust, outBiases), axis=1)
outWeightsRobust = np.matrix('1 1 1 1 0.5')
outsRobust = unitStep(np.matmul(outWeightsRobust, hiddenOutsRobust.T))
print(outsRobust)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [18]:
hiddenOuts = unitStep(np.matmul(hiddenWeights,inputsNoise.T))
hiddenOuts = hiddenOuts.T
outBiases = np.ones([400,1])
outBiases[outBiases > 0] = -1
hiddenOuts = np.concatenate((hiddenOuts, outBiases), axis=1)
outWeights = np.matrix('2 3 4 5 1')
outs = unitStep(np.matmul(outWeights, hiddenOuts.T))
print(outs)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.
  1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1.
  0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 

In [19]:
inputsCheckRobust = inputsRobust[:,0:4]
checkOuts = list()

for i in range(400):
    checkOuts.append(logicFnc(inputsCheckRobust[i,:]))

print(checkOuts)

[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

In [20]:
true_cnt_normal = 0
for i in range(400):
    if(checkOuts[i] == outs[0,i]):
        true_cnt_normal += 1
print('Accuracy = ' + str(true_cnt_normal/400*100) + "%")

Accuracy = 87.5%


In [21]:
true_cnt_robust = 0
for i in range(400):
    if(checkOuts[i] == outsRobust[0,i]):
        true_cnt_robust += 1
print('Accuracy = ' + str(true_cnt_robust/400*100) + "%")

Accuracy = 90.25%


In [22]:
print(true_cnt_normal,true_cnt_robust)

350 361
